if (NOT DEFINED GBA_EXECUTABLE OR NOT DEFINED TEST_DIRECTORY)
    message(FATAL_ERROR "Executable and test directory are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
# ARM B . and SWI 0x111111, little endian. Neither fixture needs a game ROM.
string(ASCII 254 255 255 234 branch)
string(ASCII 17 17 17 239 swi)
file(WRITE "${TEST_DIRECTORY}/loop with spaces.gba" "${branch}")
file(WRITE "${TEST_DIRECTORY}/unsupported.gba" "${swi}")
file(WRITE "${TEST_DIRECTORY}/empty.gba" "")

function(check_cli expected_code expected_text)
    execute_process(COMMAND "${GBA_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if (NOT "${code}" STREQUAL "${expected_code}")
        message(FATAL_ERROR "Unexpected exit code ${code}: ${output}${error}")
    endif()
    if (NOT "${output}${error}" MATCHES "${expected_text}")
        message(FATAL_ERROR "Missing expected output '${expected_text}': ${output}${error}")
    endif()
endfunction()

check_cli(0 "Usage:" --help)
check_cli(1 "Usage:")
check_cli(1 "Usage:" one.gba two.gba)
check_cli(1 "Failed to load ROM:" "${TEST_DIRECTORY}/missing.gba")
check_cli(1 "Failed to load ROM:" "${TEST_DIRECTORY}/empty.gba")
check_cli(0 "Completed the 20-instruction CPU debug run" "${TEST_DIRECTORY}/loop with spaces.gba")
check_cli(1 "Unsupported CPU instruction 0xef111111 at 0x8000000" "${TEST_DIRECTORY}/unsupported.gba")
